-- Snowflake Financial Risk Monitoring Queries

-- Daily Return Calculations

SELECT 
    DATE_VAL,
    CLOSE_PRICE,
    (CLOSE_PRICE - LAG(CLOSE_PRICE) OVER (ORDER BY DATE_VAL)) 
    / LAG(CLOSE_PRICE) OVER (ORDER BY DATE_VAL) AS DAILY_RETURN
FROM RAW_STOCK_DATA;

-- Volatility Monitoring
SELECT 
    STDDEV(DAILY_RETURN) * 100 AS VOLATILITY_PERCENTAGE,
    AVG(DAILY_RETURN) * 100 AS AVG_DAILY_RETURN_PERCENT
FROM VW_DAILY_RETURNS;
