-- Snowflake Financial Risk Monitoring Queries

-- Daily Return Calculations

SELECT
    DATE_VAL,
    SYMBOL,
    CLOSE_PRICE,
    (CLOSE_PRICE - LAG(CLOSE_PRICE) OVER (PARTITION BY SYMBOL ORDER BY DATE_VAL))
    / LAG(CLOSE_PRICE) OVER (PARTITION BY SYMBOL ORDER BY DATE_VAL) AS DAILY_RETURN
FROM RAW_STOCK_DATA;

-- Volatility Monitoring
SELECT
    SYMBOL,
    STDDEV(DAILY_RETURN) AS VOLATILITY
FROM RETURNS_TABLE
GROUP BY SYMBOL;
